# Generated by Django 4.0.4 on 2022-04-28 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Badiiy_kitoblar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Badiiy_kitoblar.muallif'),
        ),
    ]
