# Generated by Django 4.0.4 on 2022-04-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badiiy_kitoblar', '0002_kitob_muallif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='qaytarish_sana',
            field=models.DateField(null=True),
        ),
    ]
