# Generated by Django 4.0.4 on 2022-05-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Badiiy_kitoblar', '0005_speciality_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muallif',
            name='tirik',
            field=models.BooleanField(default=True),
        ),
    ]
